development:
  adapter: postgresql
  encoding: unicode
  database: brock-golden_development
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: brock-golden_production
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: brock-golden_test
  pool: 5
  username: postgres
  password: postgres